dw_academy:
  outputs:
    dev:
      dbname: dw_academy
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt
      threads: 4
      type: postgres
      user: postgres
  target: dev
